---
title: 'Data Science Homework #6'
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
```


```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(stringr)
library(shiny)

inspections <- 
  read_csv("../data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>%
  janitor::clean_names()

inspections <-
  inspections %>%
  filter(boro != "Missing") %>% 
  mutate(boro = str_to_title(boro))

#Format Date
inspections$inspection_date <- as.POSIXct(inspections$inspection_date, format = "%Y-%m-%d")
#Change value name to readable format
inspections$cuisine_description[inspections$cuisine_description == "Café/Coffee/Tea"] <- "Coffee/Tea"

library(scales)
library(plotly)
library(lubridate)
```

Column {.sidebar}
-----------------------------------------------------------------------
```{r}
cuisine = inspections %>% distinct(cuisine_description) %>% pull()


# selectInput widget
selectInput("cuisine_choice", label = h3("Select Cuisine Type"),
            choices = cuisine)


boro_choice = inspections %>% distinct(boro) %>% pull()

# radioButtons widget
radioButtons("boro_choice", label = h3("Choose boro"),
    choices = boro_choice, 
    selected = "Manhattan")




#dateRangeInput("date_range", label = h3("Select date range"),
                                        #startview = "year") 


```

Row
-----------------------------------------------------------------------
### Inspection Scores Over Time

```{r}

renderPlotly( {ggplotly(
  inspections %>%
    na.omit() %>%
    filter(boro == input$boro_choice) %>%
    ggplot(aes(x = inspection_date, y = score)) +
      geom_hex() +
      xlab("Date") + ylab("Inspection Score") +
      ggtitle("Inspection Scores Over Time") +
      scale_x_datetime(labels = date_format("%Y-%m-%d")))
})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Inspection Scores Boxplot

```{r}
renderPlotly( {ggplotly(
    inspections %>% 
    na.omit() %>%
    filter(cuisine_description == input$cuisine_choice) %>%
    ggplot(aes(x = boro, y = score , fill = boro)) + 
      geom_boxplot(aes(group = boro)) +
      labs(title = "Inspection Scores by Boro")  + 
      theme(legend.position = "none"))
} )
```


### Coffee/Tea Shops Barplot

```{r}

#Subset by Korean cuisine
coffee_tea_locations <- inspections[inspections$cuisine_description == "Coffee/Tea",] %>%
  select(boro) %>%
  table() %>%
  as.data.frame()
coffee_tea_locations$boro <- coffee_tea_locations$.
coffee_tea_locations <- coffee_tea_locations[c(3,2)]
coffee_tea_locations$Freq <- as.numeric(coffee_tea_locations$Freq)
coffee_tea_locations$boro <- as.factor(coffee_tea_locations$boro)
#Plot frequency of Coffee Tea Shops per Borough
coffee_tea_locations %>%
  ggplot(aes(x = boro, y = Freq, fill = boro)) + 
  geom_bar(stat = "identity") + 
  labs(title = "Number of Coffee/Tea Shops in each NYC Borough", 
       y = "Number of Shops", x = "Borough") + 
  theme(legend.position = "none")

#interactivity
coffee_tea_locations_plot <- ggplot(coffee_tea_locations, aes(x = boro, y = Freq, fill = boro)) +
  geom_bar(stat = "identity") + 
  labs(title = "Number of Coffee/Tea Shops by Boro", 
       y = "Count", x = "Borough") + 
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 1)) 
ggplotly(coffee_tea_locations_plot)
```